version: '3.8'

services:
  compiler:
    build:
      context: ./compiler
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - tectonic_cache:/root/.cache/Tectonic

volumes:
  tectonic_cache:
